### ISSUE TITLE
Test to see if current contributor completed tasks from state file when they are dropped

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#123]
Test to see if current contributor/verifier `completed_tasks` should be removed/moved when a participant is dropped and tasks need to be recomputed. The tasks declared in the state file should be updated correctly when a participant is dropped.

**Comment by apruden2008** [comment]
@kellpossible is this still relevant?

**Comment by kellpossible** [comment]
probably still relevant, but I think I mentioned it to Howard and he thought it wasn't a priority to fix
