### ISSUE TITLE
Remove the pinned rustc version

### ISSUE THREAD

**Issue by ibaryshnikov** [AleoHQ/aleo-setup#148]
As we are affected by the regression in rust stable 1.49.0, there's a need to pin rustc version in CI to 1.48.0. The pinned version should be removed once the fix is out, it may happen in point release or next major release (1.49.1 or 1.50.0)
Bug in rustc: https://github.com/rust-lang/rust/issues/79904
rustc version was pinned in #147

**Comment by apruden2008** [comment]
@ibaryshnikov have we already fixed this issue?

**Comment by ibaryshnikov** [comment]
Nope, we decided to stick with old nightly

**Comment by ibaryshnikov** [comment]
Fixed by #317 and #318
