### ISSUE TITLE
Add additional tests to ensure the round completes properly

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#226]
At the moment, the tests for round completion only check to make sure that all chunks are unlocked and have been verified. Add additional tests to ensure that the round has completed correctly. This should at a minimum include a test that the transcript has been properly updated with the current round information and stored correctly. 

phase1-coordinator/src/objects/round.rs
```
#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::prelude::*;

// (snip)

    #[test]
    #[serial]
    fn test_is_complete() {
        initialize_test_environment(&TEST_ENVIRONMENT);

        // TODO (howardwu): Add tests for a full completeness check.
        let round_0 = test_round_0_json().unwrap();
        assert!(round_0.is_complete());

        let round_0 = test_round_0().unwrap();
        assert!(round_0.is_complete());

        let round_1 = test_round_1_initial_json().unwrap();
        assert!(!round_1.is_complete());
    }
}
```

**Comment by apruden2008** [comment]
@kellpossible is this still relevant do you think? I feel like your integration test addresses this

**Comment by kellpossible** [comment]
I guess the multi-round integration tests do cover this
