### ISSUE TITLE
Verifier's completed tasks are not updated after we drop the contributor

### ISSUE THREAD

**Issue by ibaryshnikov** [AleoHQ/aleo-setup#235]
Steps to reproduce:
- add a contribution
- verify, which will move the task to "completed_tasks" for a verifier
- drop a contributor whose task was verified
- check the completed tasks of a verifier

Expected behavior: the task should be moved from "completed" to "disposed"
Actual behavior: the task stays inside "completed"

**Comment by kellpossible** [comment]
did this behaviour manifest itself as an actual bug in the ceremony?

**Comment by ibaryshnikov** [comment]
Currently if the replacement contributor tries to contribute, it encounters #232 first. After fixing #232 it will encouter this issue next. As one error gated by another error, there was no way to see this bug in the ceremony yet.
