### ISSUE TITLE
An error when contributor is dropped before contribution is verified

### ISSUE THREAD

**Issue by ibaryshnikov** [AleoHQ/aleo-setup#243]
Steps to reproduce:
- contribute once
- drop that contributor without verifying the contribution
- try to contribute with a replacement contributor

**Expected behavior:** contribution succeeds
**Actual behavior:** contribution fails with ChunkIdAlreadyAdded error

In master branch the error returned is ContributionFileSignatureLocatorAlreadyExists. This particular bug is related to #232 and fixed in #236. But the ChunkIdAlreadyAdded error is a new bug, which leads to a new test case which has not been covered before.

**Comment by apruden2008** [comment]
Closing b/c we no longer use a replacement contributor in our implementation
