### ISSUE TITLE
Participant task timeout

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/aleo-setup#252]
After watching some logic failures during integration tests where a contributor was unable to obtain a lock on a chunk indefinitely, I think it would be sensible to add some timeout for when a contributor fails to start tasks when they are available and the contributor is not currently working on a task (does not currently hold any locks). That way if for whatever reason there is some logic problem on the contributor side, or strange network problem, that allows the contributor to continue its heartbeat but it is unable to take on new available tasks, the faulty contributor will be dropped.

This feature would be beneficial for both verifiers and contributors.

**Comment by kellpossible** [comment]
I had one test where a contributor was dropped in a similar scenario, so such a drop condition may already exist, however there was not good logging for this condition. Perhaps this drop may be activated by a set number of failed requests.

**Comment by kellpossible** [comment]
I had this problem again during the development of #288

**Comment by apruden2008** [comment]
Closing since we handle now via #286
