### ISSUE TITLE
Coordinator contribributor average speed drop

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/aleo-setup#253]
If a contributor is taking too long to complete tasks on average (over a set period of time) it can be dropped. Let's say a contributor passed the initial challenge to enter the round, however once the round starts, for some reason (perhaps they are running out of RAM, or perhaps some other process on their computer kicks in, or perhaps they are being malicious) they begin to go very slowly, this will slow down everyone during the round. For a universal round this could be pretty serious.

**Comment by apruden2008** [comment]
Closing because this adds significant complexity to an already complex system
