### ISSUE TITLE
Failing integration test development 3 contributors, 2 dropped, 2 replacements

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/aleo-setup#257]
Integration test for development environment ID 8. 

+ 3 contributors
+ 2 replacement contributors
+ 1 verifier
+ 2 contributors dropped after about 10 contributions

This error appears in the coordinator log:

```txt
[2mApr 18 23:40:30.388[0m [31mERROR[0m aleo_setup_coordinator::api::contributor::try_lock: Error acquiring lock for contributor: ContributionLocatorAlreadyExists
```

Some contributions are not cleared correctly upon dropping, or replacement contributors are making contributions to the wrong chunks. Observation appears to indicate the latter is likely to be true, but I'm not sure yet.

**Comment by kellpossible** [comment]
Immediately after the contributors are dropped, there is a disconnect between the `state.json` and the files on disk. Looking at the tasks returned by `drop_participant()` https://github.com/AleoHQ/aleo-setup/blob/3451eb52cd778c220e90644a2d0dbf54d9ae7f9d/phase1-coordinator/src/coordinator_state.rs#L2089 it seems like they do not contain the dependent tasks that were also removed from other participants, therefore their files don't get deleted when the tasks are passed to `process_coordinator_state_change()` via the justification https://github.com/AleoHQ/aleo-setup/blob/3451eb52cd778c220e90644a2d0dbf54d9ae7f9d/phase1-coordinator/src/coordinator.rs#L725

**Comment by kellpossible** [comment]
I've also just discovered that some contributions from round 2 chunk 2 are present in the round state for round 1 chunk 2. Super weird!!!

**Comment by kellpossible** [comment]
Okay, it seems as though the contribution is placed into the next round's directory by the caller of `Chunk::verify_contribution()` method https://github.com/AleoHQ/aleo-setup/blob/3451eb52cd778c220e90644a2d0dbf54d9ae7f9d/phase1-coordinator/src/objects/chunk.rs#L386 which obtains its locator data from the `Coordinator::verify_contribution()` https://github.com/AleoHQ/aleo-setup/blob/3451eb52cd778c220e90644a2d0dbf54d9ae7f9d/phase1-coordinator/src/coordinator.rs#L1909 which is calculated here for the final contribution: https://github.com/AleoHQ/aleo-setup/blob/3451eb52cd778c220e90644a2d0dbf54d9ae7f9d/phase1-coordinator/src/coordinator.rs#L1792

**Comment by kellpossible** [comment]
Okay I've modified the code so that affected tasks will be scheduled to be removed from storage but there is a check in round:

https://github.com/AleoHQ/aleo-setup/blob/3451eb52cd778c220e90644a2d0dbf54d9ae7f9d/phase1-coordinator/src/objects/round.rs#L898

That doesn't pass because the contribution has already been removed. This code also looks like it should remove subsequent dependent contributions....

**Comment by apruden2008** [comment]
We've pivoted to restarting the round to address this issue
