### ISSUE TITLE
Wrong contribution id when locking a chunk

### ISSUE THREAD

**Issue by ibaryshnikov** [AleoHQ/aleo-setup#258]
Steps to reproduce:
- setup two contributors
- assign two tasks to each of them
- let the first contibutor contribute twice

**Expected behavior:** contributor should not be able to lock the second chunk because the contribution it depends on has not been done yet
**Actual behavior:** contributor locks the chunk with contribution id assigned to another contributor, then tries to contribute to it, and produces the error `ParticipantMissingPendingTask`. For example, if contributor has assigned task with chunk id 1 and contribution id 2, it locks the task with chunk id 1 and contribution id 1.

**Comment by kellpossible** [comment]
Is this issue reproducible in an integration test?

**Comment by apruden2008** [comment]
Closing because I can't reproduce this error currently
