### ISSUE TITLE
Implement PoW check for Reliability Server

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#278]
## Summary ##

In order to ensure that contributors have the capability to participate in the ceremony, we need to test to see that they meet some minimum computational/hardware requirements. Thus, we need to implement a small proof-of-work test that we send to contributors that they must complete and send back to us. If they meet the minimum requirement, we can allow them to join the ceremony

## Details ##

The BGM '17 'Powers of Tau' protocol is an MPC protocol to create parameters for a zkSNARK. Contributors to the ceremony receive a transcript, which is a list of field elements, from the coordinator (who may have received it from a prior contributor). The contributor must exponentiate each element in the field to a secret "power" or exponent. They sign and send back this mutated set of field elements to the coordinator, which passes it onto the next contributor as the new transcript. Critically, this must be deleted after the ceremony, as knowledge of this "toxic waste" could break soundness of the zk-proof scheme.

In order to minimize the likelihood that any given contributor will act maliciously, we would like as many participants as possible to contribute in the MPC ceremony. But contributions happen more or less in serial, rather than in parallel (as each participant needs to receive the transcript from the prior round). Therefore, a slow contributor is a bottleneck to the process, reducing the potential number of contributors. To ensure that the contributor has the computational power to participate in a reasonable amount of time, we require them to perform a small "proof-of-work" task which we benchmark them against before either letting them contribute or removing them from the ceremony queue. 

The test should be as similar as possible in structure to the work the contributor is performing during the actual ceremony (see phase1/compute.rs). It should be intensive enough that we can appropriately benchmark the contributor, but not so much that it takes a very long time. Once the contributor performs the task, they send it back to the coordinator which checks the work and either accepts or rejects the contributor into the ceremony. 

### Tasks ###
1) implement a PoW test based on the Powers of Tau ceremony
2) Add logic to to the coordinator which checks to see if the work was performed correctly
3) Add a parameter to the setup configuration file which allows for the coordinator to fine-tune the requirements for computational capability of the contributor

**Comment by ibaryshnikov** [comment]
Done in #297, #274 and #374
