### ISSUE TITLE
Generate an additional account key for the setup ceremony

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#282]
### Summary ###

Currently, contributors generate an Aleo account private key which derives a view key, which is used to sign contributions to a given setup round. In order to prove their participation later, we need users to generate a second account private key, which they will use to sign the view key used in the ceremony. 

### Definition

1. Contributor generates `private_key_a` with corresponding `view_key_a` and `address_a`, for use as a contributor.
2. Contributor also generates `private_key_b` with corresponding `view_key_b` and `address_b`, for use at the end of the setup ceremony.

### Details ###

For a variety of reasons it may be useful to enable contributors to prove they contributed to the ceremony after the fact, even if they participated in the ceremony anonymously. 

Using the relevant libraries in snarkVM, users should generate a second account private key after their final contribution. With this key, they will sign a message containing the view key used during the ceremony. The coordinator will check to make sure the signature is valid and save the view key and signature to verify a user's participation at a later time. 

### Steps

1. **Contributor** uses `view_key_a` to sign contribution chunks corresponding to `address_a`.
2. After completing a round of contribution, **contributor** uses `view_key_a` to sign message `address_a || address_b` (concatenated addresses) and sends this `message` and `signature` to **coordinator**.
3. **Coordinator** then checks `address_a.verify(message, signature)` is `true` and verifies that `address_b` is a well-formed Aleo address.
4. **Coordinator** then stores `message` (comprising `address_a` & `address_b`) and `signature` into its database for use as a proof of contribution by the **contributor**, and informs **contributor** that `address_b` has been saved.
5. **Contributor** now discards `private_key_a` and `view_key_a`. **Contributor** saves  `address_a`, `private_key_b`, `view_key_b`, and `address_b`.
6. **Contributor** is presented an option to publish an attestation under their identity with address_a. For the browser, I believe we have "Share" options at the end already, however need to incorporate address_a as part of the message being shared.

### Remark

- We will need to port/confirm the port of the "`view_key` to ` address` signing scheme" in `snarkos_toolkit/account` into `snarkvm_dpc/account`

**Comment by howardwu** [comment]
Here's the procedure for the second Aleo private key.

### Definition

1. Contributor generates `private_key_a` with corresponding `view_key_a` and `address_a`, for use as a contributor.
2. Contributor also generates `private_key_b` with corresponding `view_key_b` and `address_b`, for use at the end of the setup ceremony.

### Steps

1. **Contributor** uses `view_key_a` to sign contribution chunks corresponding to `address_a`.
2. After completing a round of contributions, **contributor** uses `view_key_a` to sign message `address_a || address_b` (concatenated addresses) and sends `message` and `signature` to **coordinator**.
3. **Coordinator** then checks `address_a.verify(message, signature)` is `true` and verifies that `address_b` is a well-formed Aleo address.
4. **Coordinator** then stores `address_b` into its database for use as a proof of contribution by the **contributor**, and informs **contributor** that `address_b` has been saved.
5. **Contributor** now discards `private_key_a` and `view_key_a`. **Contributor** saves  `address_a`, `private_key_b`, `view_key_b`, and `address_b`.

### Remark

- We will need to port/confirm the port of the `view_key` to ` address` signing scheme in `snarkos_toolkit/account` into `snarkvm_dpc/account`

@kobigurk could you review this when you have a few minutes and confirm this looks correct to you?

@Pratyush @raychu86 it would be great to get your review as well if possible.

**Comment by kobigurk** [comment]
Yep, I can see that working! This `address_b` is a bit less trust worthy than the signatures during the ceremony, since its private key might be stolen later. It's great that `private_key_a` and `view_key_a` get deleted.

Tangentially, one key part that I wanted to make sure we have is a connection to a real-world identity. As our goal is to inspire trust that not all contributors are actually @apruden2008, we'd like a real world identity attesting that `address_a` was them. Does that exist in the flow?

**Comment by howardwu** [comment]
That's a great point. We should provide a "one-click" link for CLI/Desktop participants to publish an attestation under their identity with `address_a`. For the browser, I believe we have "Share" options at the end already, however need to incorporate `address_a` as part of the message being shared.

**Comment by kobigurk** [comment]
Yep, that would be great!
