### ISSUE TITLE
Transition from zexe_algebra/snarkos_toolkit to snarkVM

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#284]
Currently, much of the aleo-setup repository depends on zexe-algebra. This dependency is either direct, or indirect through another library in snarkOS. However, we've implemented all of the required logic in our own repo (snarkVM), and therefore snarkos_toolkit is being deprecated. In order to ensure consistency and minimize external dependencies, we should migrate all of our code over to depend on snarkVM

**Comment by ibaryshnikov** [comment]
Done in #317
