### ISSUE TITLE
Setup Contributor Log Message Delay

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#300]
## Issue ##

After a contribution, the contributor logs continuously emit a "Successfully Contributed" message, and continue emitting even after 

## Motivation ##

Right now, the default verbosity of our logs is too high, and messages are emitted too frequently. This may confuse users, particularly in the scenario where they completed their contribution, but perhaps missed the single relevant log message that states "it is now safe to exit the program."

## Proposed Solution

Introduce a delay for informational messages (such as the message above) so the default verbosity is not too overwhelming for the user. Also, the program should stop logging after the contribution is complete.

**Comment by ibaryshnikov** [comment]
I believe this was solved in #345 , wasn't it? @apruden2008
