### ISSUE TITLE
Setup Ceremony Data Server

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/aleo-setup#301]
## Issue ##

As of now, there is no backend mechanism to collect data and store data about the setup ceremony which can be used to power the "Stats" page, on the setup frontend: https://setup-staging.aleo.org/stats. In addition, by moving towards making the coordinator stateless, we remove additional complexity. Particular data that is needed is listed below. The fields below should have user public key (or some way to identify unique contributor) as a DB key.

1) Number of successful contributions (integer) - for stats page
2) Total transcript size (float) - for stats page
3) average contribution time (string) - for stats page
4) ETH Address (string) - for user to receive NFT token as a thank-you
5) Which ceremony the user completed (string, choose from "universal", "outer", or "inner"
6) Whether they *started* a round (boolean)
7) Whether a they *finished* a round (boolean)
7) Number of previous rounds contributor has dropped from (int)
8) Contributor address (string, or other encoding)
10) Whether the user is banned (boolean) 

## Motivation ##

The purpose of the setup ceremony is to involve as many distinct contributors in the process of generating parameters for the zkSNARK scheme as possible. This is important because the security of a zkSNARK scheme relies on a single, honest contributor. By showing number of contributions and transcript size, we can provide confidence to our community about the security of the setup, and inspire them to contribute if they haven't already. 

In addition, having a database to save information about certain contributors will help reduce the state that the coordinator has to maintain and manage. This creates a more redundant and robust system. Furthermore, it allows us better keep track of important data about the contributors that will be relevant either later in the ceremony, or after the fact. 

A possible downside to this architecture is that it requires communication between the coordinator and this server. We should ensure we test the various failure modes and create additional redundancy at the infrastructure level (aka replicating the DB)

**Comment by apruden2008** [comment]
I think one solution to this might be to add fields in our existing SQLite DB for contributors. Basically we add contribution time, and IP/location, and then our server can just serve that DB?

**Comment by kellpossible** [comment]
We could also add these items as fields to the transcript coordinator.json file, and then just serve that file like in https://github.com/AleoHQ/aleo-setup-state-monitor then you could also use some of the other fields in there for the stats page like the current number of contributors, the current round, etc

**Comment by apruden2008** [comment]
@julesdesmit latest suggestion was to just run this on the coordinator. @julesdesmit feel free to expand on that.

**Comment by julesdesmit** [comment]
This issue has been finished, as the stats server is now ready and working.
