### ISSUE TITLE
Handle accepted task handoff for verifiers

### ISSUE THREAD

**Issue by julesdesmit** [AleoHQ/aleo-setup#305]
While testing for #252, I noticed that my test failed due to the pending task not having any way of being reassigned, as there were no verifiers left. This doesn't seem to be a problem in any of the other timeout tests, which seems like a bug to me - those tasks still should be handed off, but they apparently just kind of disappear.

The `drop_participant` logic should be updated so that all verifier tasks are handed off properly.

**Comment by kellpossible** [comment]
More generally we should test what happens when verifiers are dropped from the ceremony at least in the integration tests, and ensure that it doesn't stall

**Comment by kellpossible** [comment]
This line should be investigated more: https://github.com/AleoHQ/aleo-setup/pull/288#discussion_r671719373
