### ISSUE TITLE
Create a benchmark tool for contributor

### ISSUE THREAD

**Issue by zosorock** [AleoHQ/aleo-setup#349]
So we can accurately access if they can contribute in a timely manner. Suggestion is to add the tool to the `generate` function so it will only generate a key if it can meet the requirements. The measurement would then be added to the key and posted to the Coordinator on first contact.

**Comment by zosorock** [comment]
I tried to run the reliability score and it just exited after the 3rd message. No error, nothing:

```
Aug 18 00:20:53.218  INFO setup1_contributor::commands::contribute: Checking reliability score before joining the queue
Aug 18 00:21:40.598  INFO phase1::initialization: phase1-initialization complete
Aug 18 00:21:41.414  INFO phase1::computation: starting...
```

**Comment by ibaryshnikov** [comment]
@zosorock is it solved by the docker container which you've made?

**Comment by apruden2008** [comment]
closed in favor of reliability checks by coordinator and Docker benchmarker
