### ISSUE TITLE
Drop `Storage` abstraction, and work directly with directories on the filesystem

### ISSUE THREAD

**Issue by julesdesmit** [AleoHQ/aleo-setup#360]
The abstraction was originally there to help us switch backends if we needed to, but it restricts us in what we can work with when it comes to using the Disk storage like we currently do - we can't work with directories or anything, as everything needs to be done through locators.

**Comment by kellpossible** [comment]
We could still operate through locators, but extend them to support the notion of a directory, easier to do now that we don't need to abstract over all types of storage
