### ISSUE TITLE
Contributor does not allow exit without tweeting

### ISSUE THREAD

**Issue by zosorock** [AleoHQ/aleo-setup#366]
The Contributor app currently does not allow you to end your contribution without tweeting about it. If you enter nothing, or any number, it does not give you the option to simply exit.

**Comment by julesdesmit** [comment]
That shouldn't be the case, the y/n prompt should give users the option to exit if they don't want to tweet. Does this not work?

**Comment by apruden2008** [comment]
Closing b/c can't be replicated
