### ISSUE TITLE
Using docker contributor with new coordinator failed to get in the queue

### ISSUE THREAD

**Issue by julesdesmit** [AleoHQ/aleo-setup#375]
This is a potential bug which should be investigated further.

**Comment by zosorock** [comment]
Did you get any messages with it? While I was setting up the new binaries yesterday I noticed that some versions did not match (meaning they were not all newer).

**Comment by julesdesmit** [comment]
Not that I know of, it was Alex's run so he may have something left over but I doubt it. He told me it was just infinitely waiting for chunks - I did see try_lock attempts in the logs but no entries indicating it entered the queue

**Comment by apruden2008** [comment]
Multiple contributions through docker have happened since this report, can't replicate locally. Closing
